#!/usr/bin/env node

var path = require("path");
var cp = require("child_process");

try {
  cp.execSync("git status").toString();
} catch(e) {
  process.exit(1);
}

var gitCutlass = require("./lib/app");
gitCutlass.run();
