#!/usr/bin/env node

var fs = require("fs");
var path = require("path");

try {
  fs.statSync(path.join(process.cwd(), ".git"));
} catch(e) {
  console.error("This is not a git repository folder!");
  process.exit(1);
}

var gitCutlass = require("./lib/app");
gitCutlass.run();
