#!/usr/bin/env node

var fs = require("fs");

try {
  var stats = fs.statSync(".git");
  var gitCutlass = require("./lib/app");
  gitCutlass.run();
} catch(e) {
  console.error("This is not a git repository folder!");
  process.exit(1);
}
